// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ext_in_cpp
List ext_in_cpp(const arma::mat& x, int maxiter, int blocksize, double lrate, int kurt_size, double annealdeg, double annealstep, double tol, bool extended, bool verbose);
RcppExport SEXP _infomax_ext_in_cpp(SEXP xSEXP, SEXP maxiterSEXP, SEXP blocksizeSEXP, SEXP lrateSEXP, SEXP kurt_sizeSEXP, SEXP annealdegSEXP, SEXP annealstepSEXP, SEXP tolSEXP, SEXP extendedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type blocksize(blocksizeSEXP);
    Rcpp::traits::input_parameter< double >::type lrate(lrateSEXP);
    Rcpp::traits::input_parameter< int >::type kurt_size(kurt_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type annealdeg(annealdegSEXP);
    Rcpp::traits::input_parameter< double >::type annealstep(annealstepSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type extended(extendedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(ext_in_cpp(x, maxiter, blocksize, lrate, kurt_size, annealdeg, annealstep, tol, extended, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_infomax_ext_in_cpp", (DL_FUNC) &_infomax_ext_in_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_infomax(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
