# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMapMatMult <- function(A, B) {
    .Call(`_infomax_eigenMapMatMult`, A, B)
}

eigenMatMult <- function(A, B) {
    .Call(`_infomax_eigenMatMult`, A, B)
}

eigAddBis <- function(A, B, bias) {
    .Call(`_infomax_eigAddBis`, A, B, bias)
}

