# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Core Extended Infomax ICA (C++ backend)
#'
#' Internal C++ implementation of the mini-batch stochastic gradient descent
#' Infomax/Extended-Infomax algorithm. Called by \code{run_infomax()} when
#' \code{backend = "cpp"}.
#'
#' @param x Data matrix, samples in rows, components in columns (n_samps x n_comps).
#' @param maxiter Maximum number of outer iterations.
#' @param blocksize Mini-batch size.
#' @param lrate Initial learning rate.
#' @param kurt_size Number of samples for kurtosis estimation.
#' @param annealdeg Angle threshold for learning rate annealing.
#' @param annealstep Learning rate multiplier on annealing.
#' @param tol Convergence tolerance on squared weight change.
#' @param extended If TRUE, run Extended Infomax (tanh + kurtosis sign adaptation).
#' @param verbose If TRUE, print progress each iteration.
#' @return A list with \code{weights} (n_comps x n_comps) and \code{iter} (int).
#' @keywords internal
ext_in_cpp <- function(x, maxiter, blocksize, lrate, kurt_size, annealdeg, annealstep, tol, extended, verbose) {
    .Call('_infomax_ext_in_cpp', PACKAGE = 'infomax', x, maxiter, blocksize, lrate, kurt_size, annealdeg, annealstep, tol, extended, verbose)
}

